spring.datasource.url=jdbc:postgresql://dpg-cjhshp5mrchc73asugh0-a.frankfurt-postgres.render.com/bankms
spring.datasource.username=bankms_user
spring.datasource.password=HL3l7cd9fmAVsPYhUzO9hq0jUjxuOg7R

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

server.tomcat.accesslog.enabled=true

## For Email Notification
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=e0a6b034ec3e34
spring.mail.password=c17be58eb4825b
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true